### ISSUE TITLE
Detect xonsh by detecting `python`

### ISSUE THREAD

**Issue by wolfv** [mamba-org/rattler#303]
I think `xonsh` is currently not properly detected, because it appears as some `python ... -m xonsh` process or similar. 

We should see if we can make the detection more robust.

**Comment by baszalmstra** [comment]
@wolfv is this solved by #307 ?

**Comment by wolfv** [comment]
I thought it was, but it still doesn't work on my machine. I'll test some more.
